version: '0.9'

services:
  db:
    image: postgres:16
    container_name: library_db
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivanyatsuk
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: library_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:ivanyatsuk@db:5432/library
      VERSION: 1.0.0

volumes:
  postgres_data: